//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stuff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stuff()
        {
            this.Stuff_Attendence = new HashSet<Stuff_Attendence>();
        }
    
        public int id { get; set; }
        public string stuff_fullname { get; set; }
        public string stuff_about { get; set; }
        public string stuff_photo { get; set; }
        public Nullable<int> stuff_gender_id { get; set; }
        public Nullable<int> stuff_marriage_status_id { get; set; }
        public string stuff_phone { get; set; }
        public string stuff_email { get; set; }
        public string stuff_password { get; set; }
        public string stuff_address { get; set; }
        public Nullable<int> stuff_salary { get; set; }
        public Nullable<System.DateTime> stuff_birthday { get; set; }
        public Nullable<System.DateTime> stuff_start_date { get; set; }
        public Nullable<System.DateTime> stuff_start_time { get; set; }
        public Nullable<System.DateTime> stuff_finish_time { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual MarrigeStatu MarrigeStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stuff_Attendence> Stuff_Attendence { get; set; }
    }
}
